name: DoubleJumpMinus
main: net.thegamingcraft.DoubleJump.Main
version: 1.1
commands:
   fly:
       description: Toggles ability to Fly
       usage: /fly
       permission: DJN.fly
permissions:
   DJN.*:
     description: Gives access to all double jump plus features
     children:
       DJN.doubleJump: true
       DJN.groundPound: true
       DJN.damage: true
       DJN.fly: true
     default: op
   DJN.doubleJump:
     description: Allows you to use double jump
     default: not op
   DJN.groundPound:
     description: Allows you to use ground pound
     default: not op
   DJN.damage:
     description: Do damage with a groundpound
     default: not op
   DJN.fly:
     description: Allows you to fly
     default: false
